name: Minecraft Bedrock AFK Bot

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '*/15 * * * *'

jobs:
  run-bedrock-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install NPM Dependencies
        run: npm install

      - name: Execute Bedrock Bot
        run: node bot.js
        timeout-minutes: 25
